spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    #    defer-datasource-initialization: true # ?????? ??? ?? ?? data.sql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet: # ????? ??
    multipart:
      max-file-size: 2KB
      max-request-size: 2KB

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: indiego-fileupload/profileimage
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error